name: Build and Deploy Typescript App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build and compile
        run: npm run build

      - name: Archive files
        uses: actions/upload-artifact@v2
        with:
          name: typescript-app
          path: dist/

      - name: Deploy to GitHub Pages
        uses: actions/github-pages@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: dist